In [ ]:
# IMPORTING NUMPY

In [1]:
import numpy as np

In [ ]:
# ARRAYS

In [5]:
x = np.array([0, 1, 2, 3])

In [6]:
x

array([0, 1, 2, 3])

In [8]:
w = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

In [9]:
w

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [11]:
y = np.arange(8).reshape(2, 4)

In [12]:
y

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [16]:
y2 = np.arange(12).reshape(3, 4)

In [17]:
y2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
# ELEMENT WISE AND AGGREGATOR FUNCTIONS

In [19]:
x = np.array([0, 1, 2, 3])

In [20]:
## Square each value
print(np.square(x))
## Square root of each value
print(np.sqrt(x))
## Cosine of each value
print(np.cos(x))

[0 1 4 9]
[0.         1.         1.41421356 1.73205081]
[ 1.          0.54030231 -0.41614684 -0.9899925 ]


In [23]:
x = np.array([0, 1, 2, 3])
## Find the maximum value
print(np.max(x))
## Find the minimum value
print(np.min(x))
## Find the mean of the input array
print(np.mean(x))
## Find the standard deviation of the input array
print(np.std(x))

3
0
1.5
1.118033988749895


In [24]:
# IMPORTING PANDAS

In [41]:
import pandas as pd

In [26]:
# THE DATA FRAME

In [27]:
my_array = np.array([['Montgomery', 'Yellohammer state', 52423],
                    ['Sacramento', 'Golden state', 163707],
                    ['Oklahoma City', 'Sooner state', 69960]])
df = pd.DataFrame(my_array)
df

0                  1       2
0     Montgomery  Yellohammer state   52423
1     Sacramento       Golden state  163707
2  Oklahoma City       Sooner state   69960

In [29]:
df.columns = ['Capitol', 'Nickname', 'Area']
df.index = ['Alabama', 'California', 'Oklahoma']
df

Capitol           Nickname    Area
Alabama        Montgomery  Yellohammer state   52423
California     Sacramento       Golden state  163707
Oklahoma    Oklahoma City       Sooner state   69960

In [30]:
df2 = pd.DataFrame(
    my_array,
    columns = ['Capitol', 'Nickname', 'Area'],
    index = ['Alabama', 'California', 'Oklahoma'])
df2

Capitol           Nickname    Area
Alabama        Montgomery  Yellohammer state   52423
California     Sacramento       Golden state  163707
Oklahoma    Oklahoma City       Sooner state   69960

In [31]:
# ADDING MORE DATA

In [62]:
import numpy as np
import pandas as pd

# This list will beocme our row names.
names = ['George','John','Thomas','Andrew','James','Martin','William','Zachary','Millard','Franklin']
names

['George',
 'John',
 'Thomas',
 'Andrew',
 'James',
 'Martin',
 'William',
 'Zachary',
 'Millard',
 'Franklin']

In [63]:


# Create an empty data frame with names rows.
purchases = pd.DataFrame(index=names)

# Add our columns to the data frame one at a time.
purchases['country'] = ['US', 'CAN', 'CAN', 'US', 'CAN', 'US', 'US', 'US', 'CAN', 'US']
purchases['ad_views'] = [16, 42, 32, 13, 63, 19, 65, 23, 16, 77]
purchases['items_purchased'] = [2, 1, 0, 8, 0, 5, 7, 3, 0, 5]
purchases

country  ad_views  items_purchased
George        US        16                2
John         CAN        42                1
Thomas       CAN        32                0
Andrew        US        13                8
James        CAN        63                0
Martin        US        19                5
William       US        65                7
Zachary       US        23                3
Millard      CAN        16                0
Franklin      US        77                5

In [64]:
# This list will become our row names.
names = ['George',
         'John',
         'Thomas',
         'James',
         'Andrew',
         'Martin',
         'William',
         'Zachary',
         'Millard',
         'Franklin']

# Create an empty data frame with named rows.
purchases = pd.DataFrame(index=names)

# Add our columns to the data frame one at a time.
purchases['country'] = ['US', 'CAN', 'CAN', 'US', 'CAN', 'US', 'US', 'US', 'CAN', 'US']
purchases['ad_views'] = [16, 42, 32, 13, 63, 19, 65, 23, 16, 77]
purchases['items_purchased'] = [2, 1, 0, 8, 0, 5, 7, 3, 0, 5]
purchases 

country  ad_views  items_purchased
George        US        16                2
John         CAN        42                1
Thomas       CAN        32                0
James         US        13                8
Andrew       CAN        63                0
Martin        US        19                5
William       US        65                7
Zachary       US        23                3
Millard      CAN        16                0
Franklin      US        77                5

In [66]:
# Creating a new column out of our previous data
purchases['items_purch_per_ad'] = purchases['items_purchased']/purchases['ad_views']
purchases

country  ad_views  items_purchased  items_purch_per_ad
George        US        16                2            0.125000
John         CAN        42                1            0.023810
Thomas       CAN        32                0            0.000000
James         US        13                8            0.615385
Andrew       CAN        63                0            0.000000
Martin        US        19                5            0.263158
William       US        65                7            0.107692
Zachary       US        23                3            0.130435
Millard      CAN        16                0            0.000000
Franklin      US        77                5            0.064935

In [67]:
# Just to see values of a column you can just not assign the function
purchases['items_purchased']/purchases['ad_views']

George      0.125000
John        0.023810
Thomas      0.000000
James       0.615385
Andrew      0.000000
Martin      0.263158
William     0.107692
Zachary     0.130435
Millard     0.000000
Franklin    0.064935
dtype: float64

In [68]:
# Selecting from a data frame
purchases['country']

George       US
John        CAN
Thomas      CAN
James        US
Andrew      CAN
Martin       US
William      US
Zachary      US
Millard     CAN
Franklin     US
Name: country, dtype: object

In [69]:
# BASIC SELECTS WITH .LOC AND .ILOC

In [70]:
purchases.loc['George']

country                  US
ad_views                 16
items_purchased           2
items_purch_per_ad    0.125
Name: George, dtype: object

In [71]:
purchases.loc[:,'country']

George       US
John        CAN
Thomas      CAN
James        US
Andrew      CAN
Martin       US
William      US
Zachary      US
Millard     CAN
Franklin     US
Name: country, dtype: object

In [72]:
purchases.loc['George', 'country']

'US'

In [73]:
purchases.iloc[1:3, 1]

John      42
Thomas    32
Name: ad_views, dtype: int64

In [74]:
purchases.iloc[3:5, 0]

James      US
Andrew    CAN
Name: country, dtype: object

In [75]:
# CONDITIONAL SELECTION

In [76]:
purchases.loc[lambda df: purchases['items_purchased'] > 1, :]

country  ad_views  items_purchased  items_purch_per_ad
George        US        16                2            0.125000
James         US        13                8            0.615385
Martin        US        19                5            0.263158
William       US        65                7            0.107692
Zachary       US        23                3            0.130435
Franklin      US        77                5            0.064935

In [77]:
purchases[purchases['items_purchased'] > 1]

country  ad_views  items_purchased  items_purch_per_ad
George        US        16                2            0.125000
James         US        13                8            0.615385
Martin        US        19                5            0.263158
William       US        65                7            0.107692
Zachary       US        23                3            0.130435
Franklin      US        77                5            0.064935

In [78]:
# GROUPS

In [79]:
purchases.groupby('country')

In [80]:
purchases.groupby('country').aggregate(np.mean)

ad_views  items_purchased  items_purch_per_ad
country                                               
CAN         38.25             0.25            0.005952
US          35.50             5.00            0.217767

In [82]:
# for just one specific column
purchases.groupby('country')['items_purch_per_ad'].mean()

country
CAN    0.005952
US     0.217767
Name: items_purch_per_ad, dtype: float64